import { useEffect, useState } from "react";
import { useQueue } from "@/hooks/use-queue";
import { Button } from "@/components/ui/button";

export default function PaymentQR({ queueId }: { queueId: number }) {
  const { confirmPayment } = useQueue();
  const [qrUrl, setQrUrl] = useState("");

  useEffect(() => {
    // Generate a dummy UPI QR code URL for demonstration
    // In production, this would be generated by your payment provider
    const dummyUpiUrl = `upi://pay?pa=cloudcares@upi&pn=Cloud%20Cares&am=500.00&cu=INR&tn=Consultation`;
    setQrUrl(`https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(dummyUpiUrl)}`);
  }, []);

  return (
    <div className="text-center">
      <div className="bg-white p-4 inline-block rounded-lg shadow-sm">
        <img src={qrUrl} alt="Payment QR Code" className="w-48 h-48" />
      </div>
      <p className="mt-4 text-sm text-muted-foreground">
        Scan with any UPI app to pay ₹500
      </p>
      <Button
        className="mt-4"
        onClick={() => confirmPayment(queueId)}
      >
        I've completed the payment
      </Button>
    </div>
  );
}
